[package]
name = "minecraft-protocol-derive"
version = "0.0.0"
authors = ["vagola <vladislavs.golubs@yandex.ru>"]
edition = "2018"
description = "Derive macro for Minecraft packet read and write"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
